"""
Django settings for dms project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_DIR = os.path.dirname(__file__)
PROJECT_PATH = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dhc+5bdz^24)q*yqw4*hsesb34oylm-woatmta@0$w$0wjhv$^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Access-Control-Allow-Origin: *

# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userauth',
    'corsheaders',
    'rest_framework.authtoken', 
    'rest_framework_docs',
    #'rest_framework_mongoengine',
    'import_export', 
    'dataroom', 
    'data_documents', 
    'debug_toolbar', 
    'emailer', 
    'guardian', 
    'myteams', 
    'mongodb_test', 
    'graphql_test',
    'storages',
    'users_and_permission',
    'qna',
    'notifications',
    'notification_track',
    # 'voting',
    'Vote',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend', 'rest_framework.filters.OrderingFilter')
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'dms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dms_new',
#         'USER': 'postgres',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'cdms',
#         'USER': 'taher',#'axat',
#         'PASSWORD': 'axat123',#'n^%kuPvJ45VUOceb',
#         'HOST': 'localhost',#'axat.ckrwnw35qoe4.ap-south-1.rds.amazonaws.com',
#         'PORT': '5432',
#     }
# }

# INSTALLED_APPS += ["django_mongoengine"]

# MONGODB_DATABASES = {
#     "default": {
#         "name": "dms_testing",
#         "host": "localhost",
#         "password": "admin",
#         "username": "admin",
#         "port" :'27017',
#         "tz_aware": True, # if you using timezones in django (USE_TZ = True)
#     },
# }

# MONGODB_DATABASES = {
#     "default": {
#         "name": "dms_testing",
#         "host": "localhost",
#         "password": "admin",
#         "username": "admin",
#         "port" :'27017',
#         "tz_aware": True, # if you using timezones in django (USE_TZ = True)
#     },
# }


DATABASES = {
   'default': {
   'ENGINE': 'django.db.backends.postgresql_psycopg2',
   'NAME': 'cdms_portal',
   'USER': 'postgresportal@postgresportal', 
   'HOST' : 'postgresportal.postgres.database.azure.com',
   'PASSWORD' : 'US!u`LKyUPpBa?',
   'PORT': '5432',
   'SSLMODE': 'true'
  }
}






# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dms',
#         'USER': 'postgres',
#         'PASSWORD': 'rajendra123',
#         'HOST': 'localhost',
#         'PORT': '8000'
#     },
#     'sqlite_db': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

#user auth model

AUTH_USER_MODEL = 'userauth.User'



# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend', 
#     'guardian.backends.ObjectPermissionBackend',
# )


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

ALLOWED_HOSTS = ['*']
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = '/accounts/login'
ACCOUNT_ACTIVATION_DAYS = 7

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER =  'test@axat-tech.com'
EMAIL_HOST_PASSWORD = 'METesting57$'#'ret84we#'
SERVER_EMAIL = 'test@axat-tech.com'
DEFAULT_FROM_EMAIL = 'DMS'

# EMAIL_HOST = 'outlook.office365.com'
# EMAIL_HOST_USER = 'user@yourdomain.com'
# EMAIL_HOST_PASSWORD = 'Y0urP@$$w0rd'
# EMAIL_USE_TLS = True
# SERVER_EMAIL = 'test@axat-tech.com'
# DEFAULT_FROM_EMAIL = 'DMS'

######################################CORS SETTING ########################################
CORS_ORIGIN_WHITELIST = (
    'localhost:4300',
    'axatcloud.com',
    'localhost:8000',
    '127.0.0.1:8000',
    '127.0.0.1:8000',
    '34.212.231.173',
    '35.164.37.158',
    'https://docs.google.com',
    '13.232.50.64',
    'https://docullystorage.blob.core.windows.net/docullycontainer/',
    'http://52.172.204.103:8000/'
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CSRF_TRUSTED_ORIGINS = (
    'localhost:4300',
    'axatcloud.com',
    'localhost:8000',
    '127.0.0.1:8000',
    '127.0.0.1:8000',
    '34.212.231.173',
    '13.232.50.64'
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'XMLHttpRequest',
)

CORS_PREFLIGHT_MAX_AGE = 86400

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
########################################END OF CORS SETTING ##############################

############################ Start of static url ######################
STATIC_PATH = os.path.join(PROJECT_PATH,'static')

STATIC_URL = '/static/' # You may find this is already defined as such.

STATIC_ROOT = os.path.join(PROJECT_PATH, 'public')

STATICFILES_DIRS = (
    STATIC_PATH,
)
########################### End of static Url  ########################
########################### Start of media url ########################
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(PROJECT_PATH, 'media/')
########################### End of media url   ########################


########################### AWS S3 Storage configuration ##############
# AWS_ACCESS_KEY_ID = 'AKIAIT2Z5TDYPX3ARJBA'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'sibtc-static'
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# AWS_S3_OBJECT_PARAMETERS = {
#     'CacheControl': 'max-age=86400',
# }
# AWS_LOCATION = 'static'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'mysite/static'),
# ]
# STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


###########################END OF S3 Storage ##########################

#################################### blob #################################

CELERY_BROKER_URL = 'amqp://localhost'

# # DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
# # STATICFILES_STORAGE = 'storages.backends.azure_storage.AzureStorage'

# DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
# STATICFILES_STORAGE = 'custom_storage.custom_azure.PublicAzureStorage'

# # DEFAULT_FILE_STORAGE = 'dms.custom_azure.AzureMediaStorage'
# # STATICFILES_STORAGE = 'dms.custom_azure.AzureStaticStorage'

# STATIC_LOCATION = "static"
# MEDIA_LOCATION = "media"

# AZURE_ACCOUNT_NAME = "csg2c6c3165ec8fx4a14x88f"
# AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
# STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
# MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'


#################################### blob #################################


MEDIA_LOCATION = "media"
MEDIA_ROOT = "http://docullystorage.backends.blob.core.windows.net/"
MEDIA_URL = "http://docullystorage.blob.core.windows.net/media/"

STATICFILES_DIRS = [
   os.path.join(PROJECT_PATH, 'static'),
]
STATIC_LOCATION = 'static'
STATIC_URL = "http://docullystorage.blob.core.windows.net/static/"

AZURE_ACCOUNT_NAME = "docullystorage"
AZURE_ACCOUNT_KEY = 'ddIGey4fa6zz/FnWjMgPm5zN35BgIEDsaY6K18dpTFpkqUAJRD6efPBpXZGdBG8ICnyWWE8Y/PPGZQ0ajUeZTw=='
AZURE_CUSTOM_DOMAIN = 'http://docullystorage.blob.core.windows.net'
AZURE_CONTAINER = "docullycontainer"

STATICFILES_STORAGE = 'dms.custom_azure.AzureStaticStorage'
DEFAULT_FILE_STORAGE = 'dms.custom_azure.AzureMediaStorage'


# Replace <...> appropriately with your information

# AzureStorage Settings
# AZURE_STORAGE_ACCOUNT = "docullystorage"
# AZURE_STORAGE_KEY = "ddIGey4fa6zz/FnWjMgPm5zN35BgIEDsaY6K18dpTFpkqUAJRD6efPBpXZGdBG8ICnyWWE8Y/PPGZQ0ajUeZTw=="
# AZURE_STORAGE_CONTAINER = "docullycontainer" # statics will use this container

# # Static Settings
# STATICFILES_STORAGE = "dms.storage.AzureStorage"
# STATIC_URL = "http://docullystorage.blob.core.windows.net/docullycontainer/"

# # Media Settings
# MEDIA_URL = 'http://storage.pepperdeck.com/docullycontainer/'
