from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^projectName/dataroom/$', DataroomApi.as_view()),
    url(r'^projectName/clone_dataroom/$', CloneDataroomApi.as_view()),
    url(r'^projectName/dataroom_folder/$', DataroomFolderApi.as_view()),    
    url(r'^projectName/dataroom_detail/(?P<pk>[0-9]+)/$', DataroomDetail.as_view()),
    url(r'^projectName/dataroom_features/(?P<pk>[0-9]+)/$', DataroomFeatures.as_view()),
    url(r'^projectName/dataroom_overview/$', DataroomOverviewApi.as_view()),
    url(r'^projectName/multiple_diclaimer_overview/$', MakeMultipleDisclaimersOverview.as_view()),
    url(r'^projectName/get_dataroom_disclaimer/(?P<pk>[0-9]+)/$', GetDataroomDisclaimer.as_view()),
	url(r'^projectName/delete_request_api/(?P<pk>[0-9]+)/$', DeleteRequestApi.as_view()),
    url(r'^projectName/archive_request_api/(?P<pk>[0-9]+)/$', ArchiveRequestApi.as_view()),
	url(r'^projectName/update_dataroom_overview_setting/(?P<pk>[0-9]+)/$', UpdateDataroomOverviewSettingApi.as_view()),
    url(r'^projectName/create_contact/$', CreateContactApi.as_view()),
    url(r'^projectName/get_all_admin/$', GetAllAdminApi.as_view()),
	url(r'^projectName/upload_dataroom_pic/(?P<pk>[0-9]+)/$', UploadDataroomPic.as_view()),
	url(r'^projectName/set_default_dataroom_pic/(?P<pk>[0-9]+)/$', SetDefaultDataroomPic.as_view()),
	url(r'^projectName/upload_dataroom_overview_video/$', UploadDataroomOverviewVideo.as_view()),
	url(r'^projectName/remove_dataroom_overview_video/(?P<pk>[0-9]+)/$', RemoveDataroomOverviewVideo.as_view()),                
	url(r'^projectName/add_new_dataroom_disclaimer/(?P<pk>[0-9]+)/$', AddNewDataroomDisclaimer.as_view()),
	url(r'^projectName/dataroom_disclaimer_api/(?P<pk>[0-9]+)/$', DataroomDisclaimerApi.as_view()),
	url(r'^projectName/dataroom_disclaimer/(?P<pk>[0-9]+)/$', DataroomDisclaimerApiView.as_view()),
	url(r'^projectName/check_2fa_permission/(?P<pk>[0-9]+)/$', Check_2fa_permission.as_view()),
	url(r'^projectName/set_2fa_permission/(?P<pk>[0-9]+)/$', Set_2fa_permission.as_view()),
	url(r'^projectName/add_new_member_to_contact_group/$', AddNewMemberToContactGroup.as_view()),
	url(r'^projectName/get_all_contacts_associated_with_the_group/(?P<pk>[0-9]+)/$', GetAllContactsAssocitaedWithTheGroup.as_view()),
	url(r'^projectName/create_dataroom_from_my_team/$', CreateDataroomFromMyTeam.as_view(), name="delete_member_from_my_team"),
	url(r'^projectName/get_dataroom_usage_details_for_graph/(?P<pk>[0-9]+)/$', DataroomUsageDetailsForGraph.as_view()),
	url(r'^projectName/download_dataroom_index_report/(?P<pk>[0-9]+)/$', DownloadDataroomIndexReportnew.as_view()),
	url(r'^projectName/upload_new_contact_csv/$', UploadNewContactCSV.as_view()),
	url(r'^projectName/download_sample_contact_csv/$', DownloadSampleContactCsv.as_view()),
    url(r'^projectName/create_datroom_contact/$', CreateDataroomContactApi.as_view()),
    url(r'^projectName/create_datroom_contact/(?P<pk>[0-9]+)/$', GetDataroomContactApi.as_view()),
	url(r'^projectName/create_new_contact_group/$', CreateContactGroup.as_view()),
	url(r'^projectName/create_new_dataroom_contact_group/(?P<pk>[0-9]+)/$', CreateDataroomContactGroup.as_view()),
	url(r'^projectName/get_dataroom_usage/$', GetDataroomUsageApi.as_view()),
	url(r'^projectName/get_dataroom_viewed/(?P<pk>[0-9]+)/$', GetDataroomViewed.as_view()),
	url(r'^projectName/get_barchart_dataroom_viewed/(?P<pk>[0-9]+)/$', getBarChartDataroomViews.as_view()),
	url(r'^projectName/get_detaroom_all_users/(?P<pk>[0-9]+)/$', GetDetaroomAllUsers.as_view()),
	url(r'^projectName/watermark_settings/(?P<pk>[0-9]+)/$', WatermarkingSettings.as_view()),
	url(r'^projectName/watermark_preview/(?P<pk>[0-9]+)/$', WatermarkPreviewServe.as_view()),
	url(r'^projectName/update_watermark_settings/$', UpdateWatermarkingSettings.as_view()),
	url(r'^projectName/archive_dataroom/(?P<pk>[0-9]+)/$', ArchiveDataroom.as_view()),
	url(r'^projectName/contact_support_trial/$', ContactSupportTrial.as_view()),
	url(r'^projectName/update_adon/$', UpdateAddon.as_view()),
	url(r'^projectName/checkfirstpage/(?P<pk>[0-9]+)/$', CheckFirstpage.as_view()),
	# (?# url(r'^projectName/dataroomdeleteapirvgg/(?P<pk>[0-9]+)/$', dataroomdeleteapirvgg.as_view()))

]
