# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='file_flag',
            field=models.BooleanField(default=False),
        ),
    ]
