# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-08 18:42
from __future__ import unicode_literals

import Vote.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_and_permission', '0006_remove_rcentupdate_text1'),
        ('dataroom', '0015_dataroom_dataroom_namefront'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0004_remove_inviteuser_dataroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryKeyNestedMixin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('userauth.user',),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('vote_created', models.DateTimeField(auto_now_add=True)),
                ('vote_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('path', models.FileField(blank=True, default='', null=True, upload_to=Vote.models.vote_directory_path_for_dataroom)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('vote_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='VoterGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomMembers')),
                ('votergroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vote.VoterGroup')),
            ],
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('result', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('vote_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomMembers')),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vote.Vote')),
            ],
        ),
    ]
