# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0009_folderdeletedownload_file_name'),
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='dataroomfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder'),
        ),
        migrations.AddField(
            model_name='vote',
            name='document_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='sizeoffileinmb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
