# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0002_auto_20200908_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='sizeoffileinmb',
        ),
        migrations.AddField(
            model_name='vote',
            name='file_size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
