# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-21 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0026_auto_20210506_1653'),
        ('qna', '0002_faq_file_flag'),
        ('myteams', '0001_initial'),
        ('users_and_permission', '0009_auto_20210312_2005'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('guardian', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('userauth', '0058_auto_20210521_1302'),
        ('data_documents', '0045_documentpagecount'),
        ('notifications', '0007_allnotifications_dataroom_member_invitation_accept'),
        ('Vote', '0003_auto_20200909_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarykeynestedmixin',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='PrimaryKeyNestedMixin',
        ),
    ]
