# Generated by Django 3.2.16 on 2024-06-26 10:17

import Vote.models
from django.db import migrations, models
import dms.custom_azure


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0004_auto_20210521_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='path',
            field=models.FileField(blank=True, default='', null=True, storage=dms.custom_azure.AzureMediaStorage(), upload_to=Vote.models.vote_directory_path_for_dataroom),
        ),
    ]
