# Generated by Django 3.2.25 on 2024-09-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0005_alter_vote_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
