# Generated by Django 3.2.25 on 2024-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0006_vote_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='pages',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
