# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-21 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myteams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('userauth', '0058_auto_20210521_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeamBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, default='#f200bd', max_length=1000, null=True)),
                ('email_background_color', models.CharField(blank=True, default='#f200bd', max_length=1000, null=True)),
                ('custom_login_border_color', models.CharField(blank=True, default='#f200bd', max_length=1000, null=True)),
                ('border_top_color', models.CharField(blank=True, default='#f200bd', max_length=1000, null=True)),
                ('branding_logo', models.ImageField(blank=True, default='default_images/my_team/branding_logo.png', null=True, upload_to=myteams.models.user_directory_path_for_my_teams_branding_logo)),
                ('email_header', models.ImageField(blank=True, default='default_images/my_team/email_header.png', null=True, upload_to=myteams.models.user_directory_path_for_my_teams_email_header_logo)),
                ('favicon_icon', models.ImageField(blank=True, default='default_images/my_team/favicon_icon.ico', null=True, upload_to=myteams.models.user_directory_path_for_my_teams_favicon_icon)),
            ],
        ),
        migrations.CreateModel(
            name='MyTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_created_at', models.DateTimeField(auto_now_add=True)),
                ('team_updated_at', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dataroom_allowed', models.IntegerField(default=0)),
                ('dataroom_admin_allowed', models.IntegerField(default=0)),
                ('my_team_logo', models.FileField(blank=True, default='default_images/my_team/myteam-default.png', null=True, upload_to=myteams.models.user_directory_path_for_my_teams_logo)),
                ('dataroom_storage_allowed', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviatation_sent', models.DateTimeField(auto_now_add=True)),
                ('invitation_expiry', models.DateTimeField(auto_now_add=True)),
                ('is_invitation_expired', models.BooleanField(default=False)),
                ('invitation_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.InvitationStatus')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_added', models.DateTimeField(auto_now_add=True)),
                ('member_updated', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('member_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_added_by', to=settings.AUTH_USER_MODEL)),
                ('myteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to='myteams.MyTeams')),
            ],
        ),
        migrations.AddField(
            model_name='teammemberinvitation',
            name='team_members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='myteams.TeamMembers'),
        ),
        migrations.AddField(
            model_name='myteambranding',
            name='my_team_branding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyTeams', to='myteams.MyTeams'),
        ),
        migrations.AddField(
            model_name='myteambranding',
            name='my_team_branding_done_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_teams_branding_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
