# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-21 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteams',
            name='onlinesubscriber',
            field=models.BooleanField(default=False),
        ),
    ]
