# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteams', '0002_myteams_onlinesubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteams',
            name='usage_alertemail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
