# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-09 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myteams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myteams', '0003_myteams_usage_alertemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mychanels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_created_at', models.DateTimeField(auto_now_add=True)),
                ('chanel_updated_at', models.DateTimeField(auto_now_add=True)),
                ('chanel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dataroom_allowed', models.IntegerField(default=0)),
                ('dataroom_admin_allowed', models.IntegerField(default=0)),
                ('chanel_logo', models.FileField(blank=True, default='default_images/my_team/myteam-default.png', null=True, upload_to=myteams.models.user_directory_path_for_my_chanel_logo)),
                ('dataroom_storage_allowed', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('usage_alertemail', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_alertemailtwo', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_exceed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deleted_request', models.BooleanField(default=False)),
                ('is_deleted_requestat', models.DateTimeField(blank=True, null=True)),
                ('is_deleted_deletedat', models.DateTimeField(blank=True, null=True)),
                ('chanel_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chanel_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
