# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-09 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myteams', '0004_mychanels'),
    ]

    operations = [
        migrations.CreateModel(
            name='chanelMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_added', models.DateTimeField(auto_now_add=True)),
                ('member_updated', models.DateTimeField(auto_now_add=True)),
                ('accesstodataroomusers', models.BooleanField(default=False)),
                ('allowtoaddnewmember', models.BooleanField(default=False)),
                ('allowtoaddnewteam', models.BooleanField(default=False)),
                ('chanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myteams.Mychanels')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chanelmember', to=settings.AUTH_USER_MODEL)),
                ('member_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chanelmemberaddedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myteams',
            name='chanel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myteams.Mychanels'),
        ),
        migrations.AddField(
            model_name='myteams',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myteams',
            name='is_deleted_deletedat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myteams',
            name='is_deleted_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myteams',
            name='is_deleted_requestat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myteams',
            name='storage_exceed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myteams',
            name='usage_alertemailtwo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='accesstodataroomusers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='allowtoaddnewdataroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='allowtoaddnewmember',
            field=models.BooleanField(default=False),
        ),
    ]
