# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0058_auto_20210521_1302'),
        ('myteams', '0005_auto_20210609_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='chanelMemberInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviatation_sent', models.DateTimeField(auto_now_add=True)),
                ('invitation_expiry', models.DateTimeField(auto_now_add=True)),
                ('is_invitation_expired', models.BooleanField(default=False)),
                ('chanel_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myteams.chanelMembers')),
                ('invitation_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.InvitationStatus')),
            ],
        ),
    ]
