# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-08 00:47
from __future__ import unicode_literals

import dataroom.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0004_remove_inviteuser_dataroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myteams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=1000)),
                ('group_created_date', models.DateTimeField(auto_now_add=True)),
                ('group_modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_added', models.DateTimeField(auto_now_add=True)),
                ('member_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=300)),
                ('last_name', models.CharField(blank=True, max_length=300)),
                ('is_visible', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.IntegerField(default=15)),
                ('trial_expired', models.BooleanField(default=False)),
                ('trial_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('dataroom_name', models.CharField(blank=True, max_length=1000)),
                ('dataroom_logo', models.ImageField(blank=True, default='https://docullystorage.blob.core.windows.net/docullycontainer/images/logo.png', upload_to=dataroom.models.user_directory_path_for_dataroom)),
                ('account_level_branding', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_dataroom_on_live', models.BooleanField(default=False)),
                ('is_dataroom_cloned', models.BooleanField(default=False)),
                ('is_request_for_deletion', models.BooleanField(default=False)),
                ('is_request_for_archive', models.BooleanField(default=False)),
                ('dataroom_storage_allocated', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('dataroom_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dataroom_id', models.CharField(default='', max_length=100)),
                ('dataroom_cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='DataroomDeletionAndArchivedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_or_archived_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete_request', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('deleted_or_archived_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_or_archived_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataroom_disclaimer_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('dataroom_disclaimer', models.FileField(blank=True, null=True, upload_to=dataroom.models.user_directory_path_for_dataroom_disclaimer)),
                ('is_dataroom_disclaimer_default', models.BooleanField(default=False)),
                ('disclaimer_added_date', models.DateTimeField(auto_now_add=True)),
                ('disclaimer_updated_date', models.DateTimeField(auto_now_add=True)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='DataroomDisclaimerPreviewStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataroom_disclaimer_status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watermarking', models.BooleanField(default=False)),
                ('is_drm', models.BooleanField(default=False)),
                ('is_question_and_answers', models.BooleanField(default=False)),
                ('is_collabration', models.BooleanField(default=False)),
                ('is_ocr', models.BooleanField(default=False)),
                ('is_editor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_daily_email_updates', models.BooleanField(default=True)),
                ('choose_overview_default_page', models.BooleanField(default=True)),
                ('hide_file_indexing', models.BooleanField(default=True)),
                ('change_video_ppt', models.FileField(blank=True, null=True, upload_to=dataroom.models.user_directory_path_for_dataroom_overview)),
                ('dataroom_overview_heading', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dataroom_custom_links', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('show_multiple_times_disclaimer', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('roles', models.ManyToManyField(to='userauth.Role')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataroom_stage', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='dataroom view', max_length=50)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaidDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='Watermarking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('opacity', models.FloatField(blank=True, null=True)),
                ('rotation', models.FloatField(blank=True, null=True)),
                ('user_ipaddress', models.BooleanField(default=False)),
                ('user_name', models.BooleanField(default=False)),
                ('user_email', models.BooleanField(default=False)),
                ('current_time', models.BooleanField(default=False)),
                ('dataroom_name', models.BooleanField(default=False)),
                ('custom_text', models.CharField(blank=True, max_length=50, null=True)),
                ('vtop', models.BooleanField(default=False)),
                ('vcenter', models.BooleanField(default=False)),
                ('vbottom', models.BooleanField(default=False)),
                ('hleft', models.BooleanField(default=False)),
                ('hmiddle', models.BooleanField(default=False)),
                ('hright', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataroomdisclaimer',
            name='dataroom_disclaimer_preview_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.DataroomDisclaimerPreviewStatus'),
        ),
        migrations.AddField(
            model_name='dataroomdisclaimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='dataroom_modules',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.DataroomModules'),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='my_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myteams.MyTeams'),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacts',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroupmembers',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Contacts'),
        ),
        migrations.AddField(
            model_name='contactgroupmembers',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.ContactGroup'),
        ),
        migrations.AddField(
            model_name='contactgroupmembers',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
        migrations.AddField(
            model_name='contactgroupmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
