# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermarking',
            name='attachments',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
