# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-17 15:54
from __future__ import unicode_literals

import dataroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0002_auto_20200716_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='dataroom_logo',
            field=models.ImageField(blank=True, default='https://services.docully.com/assets/images/dataroom-icon.png', upload_to=dataroom.models.user_directory_path_for_dataroom),
        ),
    ]
