# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-02 02:18
from __future__ import unicode_literals

import dataroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0004_auto_20200717_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='dataroom_logo',
            field=models.ImageField(blank=True, default='https://docullystorage.blob.core.windows.net/docullycontainer/images/logo.png?sv=2019-10-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=4000-07-18T16:31:37Z&st=2020-07-18T08:31:37Z&spr=https&sig=aylrk2bVvDPXRyuw71YXS6fzG7chArJF%2F%2FYrX1lYrrE%3D', max_length=500, upload_to=dataroom.models.user_directory_path_for_dataroom),
        ),
    ]
