# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-05 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0007_auto_20200805_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='dataroom_logo',
            field=models.ImageField(blank=True, default='https://docullystorage.blob.core.windows.net/quickstartblobs/dataroom-icon.png', max_length=500, upload_to='https://docullystorage.blob.core.windows.net/quickstartblobs/user_<django.db.models.fields.related.ForeignKey>/<built-in function id>/logo/'),
        ),
    ]
