# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-06 11:18
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0008_auto_20200805_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='dataroom_logo',
            field=models.ImageField(blank=True, default='https://docullystorage.blob.core.windows.net/quickstartblobs/dataroom-icon.png', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='dms.custom_azure.AzureMediaStorage'), upload_to=''),
        ),
    ]
