# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-13 00:11
from __future__ import unicode_literals

import dataroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0013_auto_20200806_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='dataroom_logo',
            field=models.ImageField(blank=True, default='images/dataroom-icon.png', max_length=500, upload_to=dataroom.models.user_directory_path_for_dataroom),
        ),
    ]
