# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0014_auto_20200813_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='dataroom_nameFront',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
