# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0015_dataroom_dataroom_namefront'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdisclaimer',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroomdisclaimer',
            name='file_size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
