# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0016_auto_20200909_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='event',
            field=models.CharField(choices=[('1', 'Copy Folder'), ('2', 'Copy File'), ('3', 'Move Folder'), ('4', 'Move File'), ('5', 'Delete Folder'), ('6', 'Delete File'), ('7', 'None')], default='7', max_length=50),
        ),
    ]
