# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0017_dataroom_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='event_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='event',
            field=models.CharField(choices=[('1', 'Updated recently'), ('2', 'Copy File'), ('3', 'Move Folder'), ('4', 'Move File'), ('5', 'Delete Folder'), ('6', 'Delete File'), ('7', 'None')], default='7', max_length=50),
        ),
    ]
