# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0018_auto_20200918_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomview',
            name='event_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
