# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-18 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0019_dataroomview_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='member_event_track',
            field=models.ForeignKey(default=219, on_delete=django.db.models.deletion.CASCADE, related_name='member_event_track', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
