# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-18 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0020_dataroom_member_event_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataroom',
            name='member_event_track',
        ),
    ]
