# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0021_remove_dataroom_member_event_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomview',
            name='dataroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_view_search', to='dataroom.Dataroom'),
        ),
    ]
