# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0022_auto_20200918_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
