# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-02-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0023_auto_20201008_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
