# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0024_dataroom_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='addon_payment_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='plan_payment_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
