# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-06 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0025_auto_20210505_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
