# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0026_auto_20210506_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='storage_exceed_block',
            field=models.BooleanField(default=False),
        ),
    ]
