# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0027_dataroom_storage_exceed_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='delete_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='offlinedataroom',
            field=models.BooleanField(default=False),
        ),
    ]
