# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-12-03 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0028_auto_20210617_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='archiveequestactivityby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archiveactivityby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='deleterequestactivityby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedactivityby', to=settings.AUTH_USER_MODEL),
        ),
    ]
