# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-03-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0029_auto_20211203_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='dataroom_users_permitted',
            field=models.IntegerField(default=10000),
        ),
    ]
