# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-07-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0030_dataroom_dataroom_users_permitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='eighty_percent_mail',
            field=models.BooleanField(default=False),
        ),
    ]
