# Generated by Django 3.2.16 on 2023-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0031_dataroom_eighty_percent_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='otp_auth',
            field=models.BooleanField(default=False),
        ),
    ]
