# Generated by Django 3.2.16 on 2023-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0032_dataroom_otp_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='is_usa_blob',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='otp_auth',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
