# Generated by Django 3.2.16 on 2024-06-20 14:47

import dataroom.models
from django.db import migrations, models
import dms.custom_azure


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0033_auto_20230922_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='dataroom_logo',
            field=models.ImageField(blank=True, default='images/dataroom-icon.png', max_length=500, storage=dms.custom_azure.AzureMediaStorage(), upload_to=dataroom.models.user_directory_path_for_dataroom),
        ),
    ]
