# Generated by Django 3.2.16 on 2024-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0035_otp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='dataroom_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
