# Generated by Django 3.2.16 on 2024-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0036_dataroom_dataroom_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataroomProLiteFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_watermarking', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('proj_overview', models.BooleanField(default=False)),
                ('proj_video_intro', models.BooleanField(default=False)),
                ('custom_logo', models.BooleanField(default=False)),
                ('custom_external_link', models.BooleanField(default=False)),
                ('email_to_dataroom_upload', models.BooleanField(default=False)),
                ('google_drive_upload', models.BooleanField(default=False)),
                ('one_drive_upload', models.BooleanField(default=False)),
                ('sharepoint_upload', models.BooleanField(default=False)),
                ('dropbox_upload', models.BooleanField(default=False)),
                ('favourites', models.BooleanField(default=False)),
                ('redaction', models.BooleanField(default=False)),
                ('la_admin_access', models.BooleanField(default=False)),
                ('bulk_users_upload', models.BooleanField(default=False)),
                ('doculink_perm', models.BooleanField(default=False)),
                ('auto_expire', models.BooleanField(default=False)),
                ('module_perm', models.BooleanField(default=False)),
                ('qa_with_cat', models.BooleanField(default=False)),
                ('qa_submit', models.BooleanField(default=False)),
                ('desktop_unlimit_upload', models.BooleanField(default=False)),
                ('proj_management', models.BooleanField(default=False)),
                ('voting_perm', models.BooleanField(default=False)),
                ('proj_updates', models.BooleanField(default=False)),
                ('country_perm', models.BooleanField(default=False)),
            ],
        ),
    ]
