# Generated by Django 3.2.16 on 2024-07-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0037_dataroomprolitefeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.dataroom'),
        ),
    ]
