# Generated by Django 3.2.16 on 2024-07-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0038_dataroomprolitefeatures_dataroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='activity_tracker_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='all_user_upload_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='auto_convert_msoffice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='auto_logout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='co_current_logins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='fence_viewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='file_view_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='index_report_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='print_screen_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='self_upload_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='viewer_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='voting_report_perm',
            field=models.BooleanField(default=False),
        ),
    ]
