# Generated by Django 3.2.25 on 2024-09-13 15:39

import dataroom.models
from django.db import migrations, models
import dms.custom_azure


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0039_auto_20240729_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdisclaimer',
            name='pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataroomdisclaimer',
            name='dataroom_disclaimer',
            field=models.FileField(blank=True, null=True, storage=dms.custom_azure.AzureMediaStorage(), upload_to=dataroom.models.user_directory_path_for_dataroom_disclaimer),
        ),
    ]
