# Generated by Django 3.2.25 on 2024-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0040_auto_20240913_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdisclaimer',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
