# Generated by Django 3.2.25 on 2024-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0041_alter_dataroomdisclaimer_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='one_fifty_mb_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='two_fifty_mb_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='two_hundred_mb_mail',
            field=models.BooleanField(default=False),
        ),
    ]
