# Generated by Django 3.2.25 on 2025-10-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0042_auto_20240926_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='is_irm_protected',
            field=models.BooleanField(default=False),
        ),
    ]
