# Generated by Django 3.2.25 on 2026-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0043_dataroomprolitefeatures_is_irm_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomprolitefeatures',
            name='is_upload_restrict',
            field=models.BooleanField(default=False),
        ),
    ]
