"""
Django settings for dms project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from corsheaders.defaults import default_headers
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_DIR = os.path.dirname(__file__)
PROJECT_PATH = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'templates')
PROJECT_ROOT = os.path.normpath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dhc+5bdz^24)q*yqw4*hsesb34oylm-woatmta@0$w$0wjhv$^'

SESSION_COOKIE_AGE = 3600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

STRIPE_SECRET_KEY = "sk_test_51PgWGDKwlmjvMtQc4vAA7I9FZbhCucWQPRSs4VoHMqAadpULmrAL2conK5W1nMpWd7mXzs0Xe96PSjVBfQZrBK8d00sGeO6vVh"
STRIPE_PUBLISHABLE_KEY = "pk_test_51PgWGDKwlmjvMtQcj7r3jus2UNIqbcD0MZP5P9dDjNTCIsvFyB13jIyJuaV8dnNNdBeuU0zeH2q0OTsoXPWPIH3n00KxTdqDnE"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
                'stage.docullyvdr.com',
                '20.198.98.31',
                '20.198.98.31:8080',
                '20.198.98.31:8090',
                'localhost:4200',
                '*',
                ]

CORS_ORIGIN_REGEX_WHITELIST = [
    'https://stage.docullyvdr.com',
    'http://localhost:4200',
    # '127.0.0.1:8000',
    'http://20.198.98.31',
    'http://20.198.98.31:8080',
    'http://20.198.98.31:8090',
    # 'http://20.193.245.169',
    # 'http://20.193.245.169:8080',
    # 'http://20.193.245.169:8000',
    # 'https://services.docully.com',
    # 'https://services.docullyvdr.com',
    '*'
]

# Application definition

INSTALLED_APPS = [
    # 'apminsight.contrib.django',# 'suit',  # Commented out - missing static filesC:\Project\cdms_backend\cdms2\create_admin.bat
    # 'jet_django',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'userauth',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken', 
    # 'rest_framework_docs',
    #'rest_framework_mongoengine',
    'import_export', 
    'dataroom', 
    'mathfilters',
    'data_documents', 
    'debug_toolbar', 
    'emailer', 
    'guardian', 
    'myteams', 
    'mongodb_test', 
    'graphql_test',
    'storages',
    'ckeditor',
    'users_and_permission',
    'qna',
    'notifications',
    'notification_track',
    # 'voting',
    'Vote',
'daterange_filter',
'background_task',
    'rangefilter',
    'wkhtmltopdf',
    'disable_cache_headers.apps.DisableCacheHeadersConfig',
    

]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'data_documents.utils.custom_exception_handler'
    # 'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend', 'rest_framework.filters.OrderingFilter')
}

MIDDLEWARE = [
    "disable_cache_headers.middleware.DisableCacheControl",
    # 'csp.middleware.CSPMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'data_documents.middleware.LogRequestMiddleware',
]

ROOT_URLCONF = 'dms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dms.wsgi.application'




################################ loggging #######################################################################
from datetime import date,timedelta
import os.path
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


log_dir = os.path.join(BASE_DIR, 'log_file')
# Create log directory if it doesn't exist
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
    os.chmod(log_dir, 0o777)

filepath = os.path.join(log_dir, str(date.today()))
file_check = os.path.exists(filepath)
if not file_check:
    file = open(filepath, "w")
    file.write("############ start ##############")
    file.close()
    os.chmod(filepath, 0o777)

######## 7 days Old log file remove ####################
try:
    os.remove(os.path.join(log_dir, str(date.today()-timedelta(days=5))))
except:
    pass
###################################################################################

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(name)-12s %(levelname)-8s %(message)s'
        },
        'file': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'file',
            'filename': filepath
        }
    },
    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ['console', 'file']
        }
    }
}



# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dms_new',
#         'USER': 'postgres',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'cdms',
#         'USER': 'taher',#'axat',
#         'PASSWORD': 'axat123',#'n^%kuPvJ45VUOceb',
#         'HOST': 'localhost',#'axat.ckrwnw35qoe4.ap-south-1.rds.amazonaws.com',
#         'PORT': '5432',
#     }
# }

# INSTALLED_APPS += ["django_mongoengine"]

# MONGODB_DATABASES = {
#     "default": {
#         "name": "dms_testing",
#         "host": "localhost",
#         "password": "admin",
#         "username": "admin",
#         "port" :'27017',
#         "tz_aware": True, # if you using timezones in django (USE_TZ = True)
#     },
# }

# MONGODB_DATABASES = {
#     "default": {
#         "name": "dms_testing",
#         "host": "localhost",
#         "password": "admin",
#         "username": "admin",
#         "port" :'27017',
#         "tz_aware": True, # if you using timezones in django (USE_TZ = True)
#     },
# }


DATABASES = {
   'default': {
   'ENGINE': 'django.db.backends.postgresql_psycopg2',
   'NAME': 'cdms_portal',
   # 'USER': 'docullyuser', 
   # 'HOST' : 'docullypostgressqlazure.postgres.database.azure.com',
   # 'PASSWORD' : '8Tawzq#Rhz3OofJ6y@QKlH%6JrhXA^aU66TQ%c8x1ZeG4r$',
   'USER': 'postgreadmin', 
   'HOST' : 'docullypostgressqlazurevdr.postgres.database.azure.com',
   'PASSWORD' : '!Bzl0#3O#G^qG4DbN0JH@5*a',
   'PORT': '5432',
   'SSLMODE': 'true'
  }
}

CRONTAB_COMMAND_SUFFIX = '2>&1'

CRONJOBS = [
    ('1 0 * * *', 'emailer.cron.tempfile_deletion_job','>> tempfile_deletion_job.log'),
    ('16 3 * * *', 'userauth.cron.daily_addon_invoice_job','>> addon_cron.log'),
    ('20 0 * * *', 'userauth.cron2.daily_plan_invoice_job','>> plan_cron.log'),
    ('0 0 * * */5', 'userauth.emailtodataroom_cron.email_to_dataroom','>> emailtodataroom_cron1.log'),
    ('0 21 * * *', 'emailer.cron.my_scheduled_job','>> my_scheduled_job.log'),
    # ('30 17 * * *', 'userauth.cron3.dataroom_deletion_job','>> dataroom_deletion_cron.log'),
    ('45 17 * * *', 'userauth.overdue_accessrevoke_cron.overdue_accessrevoke_job','>> overdue_accessrevoke_job_cron.log'),
    ('0 18 * * *', 'userauth.two_daysalert_cron.daily_twoday_alert__job','>> daily_twoday_alert__jobcron.log'),
    ('15 18 * * *', 'userauth.plan_cancel_cron.daily_plan_cancel_job','>> daily_plan_cancel_job_cron.log'),
    ('0 17 * * *', 'users_and_permission.access_revoke_cron.permisionrevoke_job','>> permission_revoke.log'),
    ('1 1 */2 * *', 'userauth.email_to_dataroom_cron.renew_subscription','>> renew_subscription.log')


]

#varunn


# S247_LICENSE_KEY='in_b9d6459d323497ceafebe978a7244516'
# APM_APP_NAME='DocullyVDR'
# APM_APP_PORT='8080'
# PROXY_SERVER_HOST
# PROXY_SERVER_PORT
# PROXY_AUTH_USERNAME
# PROXY_AUTH_PASSWORD


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dms',
#         'USER': 'postgres',
#         'PASSWORD': 'rajendra123',
#         'HOST': 'localhost',
#         'PORT': '8000'
#     },
#     'sqlite_db': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

#user auth model

AUTH_USER_MODEL = 'userauth.User'



# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend', 
#     'guardian.backends.ObjectPermissionBackend',
# )



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Dubai'

USE_I18N = True

USE_L10N = False

USE_TZ = False
#to create dynamic search 'generate_blob_shared_access_signature' in all folders you will get code to generate sas_url dynamically for each file 
# sas_url='?sv=2019-10-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=4000-07-18T16:31:37Z&st=2020-07-18T08:31:37Z&spr=https&sig=aylrk2bVvDPXRyuw71YXS6fzG7chArJF%2F%2FYrX1lYrrE%3D'
# sas_url='sp=racwdli&st=2023-09-12T14:00:21Z&se=2024-08-31T22:00:21Z&spr=https&sv=2022-11-02&sr=c&sig=lrUSru11G6%2F8kp1nq4AW30xMbtdKYWJQ3EkQB4mghZk%3D'
# sas_url='?sv=2021-10-04&ss=btqf&srt=sco&st=2023-02-25T11%3A51%3A17Z&se=2024-02-25T11%3A51%3A00Z&sp=rl&sig=AWXxw55%2FTC%2BUSOIlVQC3naDahCCebIBNszSFRdqRfBc%3D'
sas_url='?sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2030-01-15T23:38:31Z&st=2026-01-15T15:23:31Z&spr=https&sig=2Q4p8SixtIll9Ve8WCdT5ghgaixc6Q0R5mOzQEFbHHU%3D'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = '/static/'

# ALLOWED_HOSTS = ['*']
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'http://20.193.245.169:8080/projectName/admin/login/'
ACCOUNT_ACTIVATION_DAYS = 7

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER =  'test@axat-tech.com'
# EMAIL_HOST_PASSWORD = 'METesting57$'#'ret84we#'
# SERVER_EMAIL = 'test@axat-tech.com'
# DEFAULT_FROM_EMAIL = 'DMS'

# EMAIL_HOST = 'outlook.office365.com'
# EMAIL_HOST_USER = 'user@yourdomain.com'
# EMAIL_HOST_PASSWORD = 'Y0urP@$$w0rd'
# EMAIL_USE_TLS = True
# SERVER_EMAIL = 'test@axat-tech.com'
# DEFAULT_FROM_EMAIL = 'DMS'

# EMAIL_HOST = 'smtp.office365.com'
# # EMAIL_HOST = 'SMTP.gmail.com'
SENDGRID_API_KEY='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'
SENDGRID_API_KEY1='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'

# # EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# # EMAIL_USE_SSL = True
# EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_USER = 'alerts@docullyvdr.com'
# # EMAIL_HOST_PASSWORD = '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'
# # EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
# EMAIL_HOST_PASSWORD = '121@Office365'
# EMAIL_USE_TLS = True
# SERVER_EMAIL = 'alerts@docullyvdr.com'
# DEFAULT_FROM_EMAIL = 'DocullyVDR Data Room Alerts <alerts@docullyvdr.com>'






EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.office365.com'  # Microsoft's SMTP server

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'alerts@docullyvdr.com'  # Your Microsoft 365 email

# EMAIL_HOST_PASSWORD = '121@Office365'  # Your Microsoft 365 email password
EMAIL_HOST_PASSWORD = 'snkhfyjxdqmnzhdl'  # Your Microsoft 365 email password

DEFAULT_FROM_EMAIL = 'DocullyVDR Data Room Alerts <alerts@docullyvdr.com>'



# EMAIL_HOST = 'smtp.zeptomail.com'  # Microsoft's SMTP server

# EMAIL_PORT = 587

# EMAIL_USE_TLS = True

# EMAIL_HOST_USER = 'bouncemails@one.docullyvdr.com'  # Your Microsoft 365 email

# EMAIL_HOST_PASSWORD = '121@Office365'  # Your Microsoft 365 email password

# DEFAULT_FROM_EMAIL = 'DocullyVDR Data Room Alerts <alerts@docullyvdr.com>'





CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = False



# CSP_DEFAULT_SRC=("'self'","http://20.198.98.31/")
# SECURE_BROWSER_XSS_FILTER = True
# X_FRAME_OPTIONS = 'DENY'
# #X-Content-Type-Options
# SECURE_CONTENT_TYPE_NOSNIFF = True
# CSRF_COOKIE_HTTPONLY=True
# SESSION_COOKIE_HTTPONLY=True
# LANGUAGE_COOKIE_HTTPONLY=True
# # SESSION_COOKIE_SECURE = True
# COOKIE_HTTPONLY=True


######################################CORS SETTING ########################################
CORS_ORIGIN_WHITELIST = (
   # 'http://localhost:4200',
   # 'axatcloud.com',
   # 'http://localhost:8000',
    # 'http://127.0.0.1:8000',
   # '127.0.0.1:8000',
   # '34.212.231.173',
   # '35.164.37.158',
    # 'https://docs.google.com',
   # '13.232.50.64',
    #'https://docullystorage.blob.core.windows.net/docullycontainer'
    # 'https://services.docully.com',
    # 'https://services.docullyvdr.com',
    # 'http://52.172.204.103:8000',
    'http://20.198.98.31:8080',
    'http://20.198.98.31',
    'https://stage.docullyvdr.com',
    'http://stage.docullyvdr.com',
    '*',
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    # 'OPTIONS',
    # 'PATCH',
    'POST',
    'PUT',
)

CSRF_TRUSTED_ORIGINS = (
    'http://stage.docullyvdr.com',
    'https://stage.docullyvdr.com',
    'http://localhost:4200',
    # 'axatcloud.com',
    # 'localhost:8000',
    # '127.0.0.1:8000',
    # '127.0.0.1:8000',
    # '34.212.231.173',
    # '13.232.50.64',
    # 'http://docully.centralindia.cloudapp.azure.com/#/',
    # 'https://services.docully.com',
    # 'https://services.docullyvdr.com',
    # 'https://secure.ccavenue.ae',
    # 'http://20.193.245.169:8000',
    # 'http://20.193.245.169:8080',
    # 'http://20.193.245.169'
    'http://20.198.98.31',
    'http://20.198.98.31:8080',
    'http://20.198.98.31:8090',
    '*'
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'XMLHttpRequest',
)

CORS_PREFLIGHT_MAX_AGE = 86400

CORS_ALLOWED_ORIGINS = [
    'https://stage.docullyvdr.com',
    'http://localhost:4200',
    # 'http://20.198.98.31:8000',
    'http://20.198.98.31:8080',
    'http://20.198.98.31',
    'http://152.59.12.146',
    'http://localhost:5000',
    'https://stage.docullyvdr.com'

]


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
########################################END OF CORS SETTING ##############################

############################ Start of static url ######################
STATIC_PATH = os.path.join(PROJECT_PATH,'static')

STATIC_URL = '/static/' # You may find this is already defined as such.

STATIC_ROOT = os.path.join(PROJECT_PATH, 'public')


WATERMARK_URL = '/projectName/watermark/'
WATERMARK_ROOT = os.path.join(PROJECT_PATH, 'Admin_Watermark/')



STATICFILES_DIRS = (
    STATIC_PATH,
)
########################### End of static Url  ########################
########################### Start of media url ########################
MEDIA_URL1 = '/projectName/media/'
MEDIA_ROOT1 = os.path.join(PROJECT_PATH, 'media/')

STATIC_URL2 = '/assets/'
STATIC_ROOT2 = os.path.join(PROJECT_PATH, 'static/assets/')
#print(MEDIA_URL1, MEDIA_ROOT2, "Media")
########################### End of media url   ########################


########################### AWS S3 Storage configuration ##############
# AWS_ACCESS_KEY_ID = 'AKIAIT2Z5TDYPX3ARJBA'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'sibtc-static'
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# AWS_S3_OBJECT_PARAMETERS = {
#     'CacheControl': 'max-age=86400',
# }
# AWS_LOCATION = 'static'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'mysite/static'),
# ]
# STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


###########################END OF S3 Storage ##########################

#################################### blob #################################

# CELERY_BROKER_URL = 'amqp://localhost'

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # URL of the Redis broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Redis backend to store task results
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# # DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
# # STATICFILES_STORAGE = 'storages.backends.azure_storage.AzureStorage'

# DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
# STATICFILES_STORAGE = 'custom_storage.custom_azure.PublicAzureStorage'

# # DEFAULT_FILE_STORAGE = 'dms.custom_azure.AzureMediaStorage'
# # STATICFILES_STORAGE = 'dms.custom_azure.AzureStaticStorage'

# STATIC_LOCATION = "static"
# MEDIA_LOCATION = "media"

# AZURE_ACCOUNT_NAME = "csg2c6c3165ec8fx4a14x88f"
# AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
# STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
# MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'


#################################### blob #################################


MEDIA_LOCATION = "media"
MEDIA_ROOT = "http://newdocullystorage.backends.blob.core.windows.net/"
MEDIA_URL = "http://newdocullystorage.blob.core.windows.net/media/"

STATICFILES_DIRS = [
   os.path.join(PROJECT_PATH, 'static'),
]
STATIC_LOCATION = 'static'
STATIC_URL = "http://newdocullystorage.blob.core.windows.net/static/"

# AZURE_ACCOUNT_NAME = "docullystorage"
# AZURE_ACCOUNT_KEY = 'vyjT1gd5pbx4rlFFo+Q+5z5c3lZBENmF3yBFP9ZjohlWO4y1f1jic39sHatukVPL8dqP4OERbWFQ+AStzUWTnQ=='
# AZURE_CUSTOM_DOMAIN = 'http://docullystorage.blob.core.windows.net'
AZURE_CONTAINER = "docullycontainer"

# STATICFILES_STORAGE = 'dms.custom_azure.AzureStaticStorage'
# DEFAULT_FILE_STORAGE = 'dms.custom_azure.AzureMediaStorage'
#madebyrushikesh
PRIVATE_STORAGE_ROOT = os.path.join(PROJECT_PATH, 'server_DocFile/')
# Using default Django storage instead of Azure to avoid SDK compatibility issues


CKEDITOR_CONFIGS = {
   'default': {
       # 'skin': 'moono',
       # 'skin': 'office2013',
       'toolbar_Basic': [
           ['Source', '-', 'Bold', 'Italic']
       ],
       'toolbar_YourCustomToolbarConfig': [
           # {'name': 'document', 'items': ['Source', '-', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
           {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
           {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
           {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
           {'name': 'about', 'items': ['About']},
           {'name': 'yourcustomtools', 'items': [
               # put the name of your editor.ui.addButton here
               'Preview',
               'Maximize',

           ]},
           # {'name': 'forms',
           #  'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
           #            'HiddenField']},
           '/',
           {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
           {'name': 'paragraph',
            'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                      'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                      'Language']},
           {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
           {'name': 'insert',
            'items': ['Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
           # '/',
           # {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
          
       ],
       'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
       # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
       # 'height': 291,
       # 'width': '100%',
       # 'filebrowserWindowHeight': 725,
       # 'filebrowserWindowWidth': 940,
       # 'toolbarCanCollapse': True,
       # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
       'tabSpaces': 4,
       'extraPlugins': ','.join([
           'uploadimage', # the upload image feature
           # your extra plugins here
           'div',
           'autolink',
           'autoembed',
           'embedsemantic',
           'autogrow',
# 'devtools',
           'widget',
           'lineutils',
           'clipboard',
           'dialog',
           'dialogui',
           'elementspath',
           'wordcount'
       ]),
   }
}
# LimitRequestBody 2147483648

# DATA_UPLOAD_MAX_MEMORY_SIZE = 209715200
DATA_UPLOAD_MAX_MEMORY_SIZE = 2147483648
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
DATA_UPLOAD_MAX_NUMBER_FILES=2000
# Replace <...> appropriately with your information
# SESSION_EXPIRE_AT_BROWSER_CLOSE =True
SESSION_SAVE_EVERY_REQUEST =True
# AzureStorage Settings
# AZURE_STORAGE_ACCOUNT = "docullystorage"
# AZURE_STORAGE_KEY = "ddIGey4fa6zz/FnWjMgPm5zN35BgIEDsaY6K18dpTFpkqUAJRD6efPBpXZGdBG8ICnyWWE8Y/PPGZQ0ajUeZTw=="
# AZURE_STORAGE_CONTAINER = "docullycontainer" # statics will use this container

# # Static Settings
# STATICFILES_STORAGE = "dms.storage.AzureStorage"
# STATIC_URL = "http://docullystorage.blob.core.windows.net/docullycontainer/"

# # Media Settings
# MEDIA_URL = 'http://storage.pepperdeck.com/docullycontainer/'


# Access-Control-Allow-Origin :'http://20.198.98.31'

