# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-21 05:12
from __future__ import unicode_literals

import data_documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_documents', '0003_auto_20200120_0438'),
        ('dataroom', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataroomGroupFolderSpecificPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_no_access', models.BooleanField(default=True)),
                ('is_access', models.BooleanField(default=False)),
                ('is_view_only', models.BooleanField(default=False)),
                ('is_view_and_print', models.BooleanField(default=False)),
                ('is_view_and_print_and_download', models.BooleanField(default=False)),
                ('is_upload', models.BooleanField(default=False)),
                ('is_watermarking', models.BooleanField(default=False)),
                ('is_drm', models.BooleanField(default=False)),
                ('is_editor', models.BooleanField(default=False)),
                ('is_shortcut', models.BooleanField(default=False)),
                ('watermarking_file', models.FileField(blank=True, null=True, upload_to='')),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='DataroomGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watermarking', models.BooleanField(default=False)),
                ('is_doc_as_pdf', models.BooleanField(default=False)),
                ('is_excel_as_pdf', models.BooleanField(default=False)),
                ('is_drm', models.BooleanField(default=False)),
                ('is_edit_index', models.BooleanField(default=False)),
                ('is_overview', models.BooleanField(default=False)),
                ('is_q_and_a', models.BooleanField(default=False)),
                ('is_users_and_permission', models.BooleanField(default=False)),
                ('is_updates', models.BooleanField(default=False)),
                ('is_reports', models.BooleanField(default=False)),
                ('is_voting', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='DataroomGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('group_created', models.DateTimeField(auto_now_add=True)),
                ('group_updated', models.DateTimeField(auto_now_add=True)),
                ('limited_access', models.BooleanField(default=False)),
                ('end_user', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('group_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomMemberInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_sent', models.DateTimeField(auto_now_add=True)),
                ('invitation_expiry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_user', models.BooleanField(default=False)),
                ('is_q_a_user', models.BooleanField(default=False)),
                ('is_q_a_submitter_user', models.BooleanField(default=False)),
                ('is_dataroom_admin', models.BooleanField(default=False)),
                ('is_la_user', models.BooleanField(default=False)),
                ('is_end_user', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deleted_end', models.BooleanField(default=False)),
                ('is_deleted_la', models.BooleanField(default=False)),
                ('disclaimer_status', models.BooleanField(default=False)),
                ('disclaimer_signed_date', models.DateTimeField(auto_now_add=True)),
                ('disclaimer_signed_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('end_user_group', models.ManyToManyField(blank=True, null=True, to='users_and_permission.DataroomGroups')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_member', to=settings.AUTH_USER_MODEL)),
                ('member_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_member_added_by', to=settings.AUTH_USER_MODEL)),
                ('member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.EndUserType')),
            ],
        ),
        migrations.CreateModel(
            name='RcentUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('send_update_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, default='', null=True, upload_to=data_documents.models.store_dataroom_files1)),
                ('document_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='data_documents.Categories')),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('group', models.ManyToManyField(blank=True, to='users_and_permission.DataroomGroups')),
                ('member', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_update_admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataroommemberinvitation',
            name='dataroom_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomMembers'),
        ),
        migrations.AddField(
            model_name='dataroommemberinvitation',
            name='invitation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.InvitationStatus'),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='dataroom_groups',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomGroups'),
        ),
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='dataroom_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomGroups'),
        ),
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder'),
        ),
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='permission_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='permission_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
