# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-21 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroommembers',
            name='end_user_group',
            field=models.ManyToManyField(blank=True, to='users_and_permission.DataroomGroups'),
        ),
    ]
