# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0003_remove_dataroomgroupfolderspecificpermissions_is_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='is_shortcut',
            field=models.BooleanField(default=False),
        ),
    ]
