# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0004_dataroomgroupfolderspecificpermissions_is_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcentupdate',
            name='text1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
