# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-25 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0005_rcentupdate_text1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcentupdate',
            name='text1',
        ),
    ]
