# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0006_remove_rcentupdate_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroommembers',
            name='event_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
