# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0007_dataroommembers_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroommembers',
            name='memberactivestatus',
            field=models.BooleanField(default=False),
        ),
    ]
