# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-03-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0008_dataroommembers_memberactivestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroommembers',
            name='disclaimer_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
