# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-08-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0009_auto_20210312_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='access_revoke',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroomgroups',
            name='access_revoke',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataroomgroups',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
