# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-06-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0010_auto_20210827_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_doc_as_pdf_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_drm_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_edit_index_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_excel_as_pdf_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_overview_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_q_and_a_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_reports_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_updates_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_users_and_permission_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_voting_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_watermarking_previous',
            field=models.BooleanField(default=False),
        ),
    ]
