# Generated by Django 3.2.16 on 2023-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0011_auto_20220628_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroommembers',
            name='disclaimer_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
