# Generated by Django 3.2.16 on 2024-08-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0058_favourite_foldertrash_redacted_pdf_redactorversion'),
        ('users_and_permission', '0012_alter_dataroommembers_disclaimer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_view_limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataroom_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_documents.dataroomfolder')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.dataroommembers')),
            ],
        ),
    ]
