# Generated by Django 3.2.16 on 2024-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0013_doc_view_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='viewer_limit_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doc_view_limit',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
