# Generated by Django 3.2.25 on 2024-12-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0014_auto_20240823_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='folder_timer_upload_ristrict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='folder_timer_upload_ristrict_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
