# Generated by Django 3.2.25 on 2025-01-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0015_auto_20241229_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='upload_ristrict_with_timer',
            field=models.BooleanField(default=False),
        ),
    ]
