# Generated by Django 3.2.25 on 2025-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0016_dataroomgrouppermission_upload_ristrict_with_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroommembers',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
