# Generated by Django 3.2.25 on 2025-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0017_dataroommembers_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_irm_protected',
            field=models.BooleanField(default=False),
        ),
    ]
