# Generated by Django 3.2.25 on 2025-10-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0018_dataroomgrouppermission_is_irm_protected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irm_group_protection_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=100, null=True)),
                ('label_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=500, null=True)),
                ('group_name', models.CharField(blank=True, max_length=500, null=True)),
                ('label_policy_name', models.CharField(blank=True, max_length=500, null=True)),
                ('label_policy_id', models.CharField(blank=True, max_length=500, null=True)),
                ('dataroom_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.dataroomgroups')),
            ],
        ),
    ]
