# Generated by Django 3.2.25 on 2025-10-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0019_irm_group_protection_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgroupfolderspecificpermissions',
            name='is_irm_protected',
            field=models.BooleanField(default=False),
        ),
    ]
