# Generated by Django 3.2.25 on 2025-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0020_dataroomgroupfolderspecificpermissions_is_irm_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='irm_group_protection_details',
            name='expiry_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
