# Generated by Django 3.2.25 on 2025-10-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0021_irm_group_protection_details_expiry_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomgrouppermission',
            name='is_irm_active',
            field=models.BooleanField(default=False),
        ),
    ]
