from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^projectName/users/$', UserView.as_view(), name="users"),
    url(r'^projectName/register/$', Register.as_view(), name="api_register"),
    url(r'^projectName/api_forgot/$', ForgotPasswordView.as_view(), name="api_forgot"),    
    url(r'^projectName/verify/$', AccountVerifyView.as_view(), name="api_verify"),
    url(r'^projectName/receive_email/$', Receive_email.as_view(), name="receive_email"),
    url(r'^projectName/login/$', LoginView.as_view(), name="api_login"),
    url(r'^projectName/logout/$', LogoutView.as_view(), name="logout"),    
    url(r'^projectName/create_password/$', CreatePasswordView.as_view(), name="create_password"),    
    url(r'^projectName/password_reset/$', password_reset, name="password_reset"),
    url(r'^projectName/password_reset_submit/$', password_reset_submit, name="password_reset_submit"), 
    url(r'^projectName/password_set/$', password_set, name="password_set"),
    url(r'^projectName/password_set_submit/$', password_set_submit, name="password_set_submit"), 
    url(r'^projectName/activate/(?P<key>.+)$',activate, name='activate'),
    url(r'^projectName/user_profile/$', UserProfile.as_view(), name="user_profile"),
    url(r'^projectName/user_profile_dataroom/(?P<pk>[0-9]+)/$', UserProfileDataroom.as_view(), name="user_profile_dataroom"),
    url(r'^projectName/category_user_profile/(?P<pk>[0-9]+)/$', CategoryUser.as_view(), name="category_user_profile"),
    url(r'^projectName/change_password/$', ChangePassword.as_view(), name="change_password"), 
    url(r'^projectName/access_history/$', AccessHistoryApi.as_view(), name="access_history"), 
    url(r'^projectName/create_user_from_superadmin/$', CreateUserFromSuperAdmin.as_view(), name="create_user_from_superadmin"), 
    url(r'^projectName/invitation_link/(?P<key>.+)$',invitation_link, name='invitation_link'),
    url(r'^projectName/welcome_login/$',invitation_welcome_login, name='invitation_welcome_login'),
    url(r'^projectName/welcome_login_success/$',invitation_welcome_login_success, name='invitation_welcome_login_success'),
    url(r'^projectName/upload_profile_pic/$', UploadProfilePic.as_view(), name="upload_profile_pic"),    
    url(r'^projectName/invitation_link_admin/(?P<key>.+)/$',invitation_link_admin, name='invitation_link_admin'),
    url(r'^projectName/admin_welcome_login/$',admin_invitation_welcome_login, name='admin_invitation_welcome_login'),
    url(r'^projectName/admin_welcome_login_success/$',admin_invitation_welcome_login_success, name='admin_invitation_welcome_login_success'),
    url(r'^projectName/inactivesessiondelete/$',inactivesessiondelete.as_view(), name='inactivesessiondelete'),
    url(r'^projectName/registeremailcheck/$',registeremailcheck.as_view(), name='registeremailcheck'),
    url(r'^projectName/plan_subscription/$',plan_subscription.as_view(), name='plan_subscription'),
    url(r'^projectName/plan_details/$',plandetails.as_view(), name='plan_details'),
    url(r'^projectName/feature_details/$',featuredetails.as_view(), name='feature_details'),
    url(r'^projectName/user_plan_redirection_flag/$',userplanredirectionflag.as_view(), name='user_plan_redirection_flag'),
    url(r'^projectName/GetSinglePlan/(?P<pk>[0-9]+)/$', GetSinglePlan.as_view(), name="GetSinglePlan"),
    url(r'^projectName/MaintainPlanSession/', MaintainPlanSession.as_view(), name="MaintainPlanSession"),
    url(r'^projectName/GetPlanForBilling/(?P<pk>[0-9]+)/$', GetPlanForBilling.as_view(), name="GetPlanForBilling"),
    url(r'^projectName/Singleusersubsubscription/(?P<pk>[0-9]+)/$', Singleusersubsubscription.as_view(), name="Singleusersubsubscription"),
    url(r'^projectName/userplandetails/(?P<pk>[0-9]+)/$', userplandetails.as_view(), name="userplandetails"),
    url(r'^projectName/addon_dvd_post/(?P<pk>[0-9]+)/$', addon_dvd_post.as_view(), name="addon_dvd_post"),
    url(r'^projectName/getusercurrentplan/(?P<pk>[0-9]+)/$', getusercurrentplan.as_view(), name="getusercurrentplan"),
    url(r'^projectName/canceluserplan/(?P<pk>[0-9]+)/$', cancel_user_plan.as_view(), name="canceluserplan"),
    url(r'^projectName/userplan_stopat_monthend/(?P<pk>[0-9]+)/$', userplan_stopat_monthend.as_view(), name="userplan_stopat_monthend"),
    url(r'^projectName/reactivate_user_plan/(?P<pk>[0-9]+)/$', reactivate_user_plan.as_view(), name="reactivate_user_plan"),
    url(r'^projectName/userplandetails_new/(?P<pk>[0-9]+)/$', userplandetails_new.as_view(), name="userplandetails_new"),
    url(r'^projectName/addon_get/(?P<pk>[0-9]+)/$', addon_get.as_view(), name="addon_get"),
    url(r'^projectName/currentplandetail/(?P<pk>[0-9]+)/$', currentplandetail.as_view(), name="currentplandetail"),
    url(r'^projectName/dataroomdeleteapirvgg/$', dataroomdeleteapirvgg.as_view(),name='dataroomdeleteapirvgg'),
    url(r'^projectName/newplan_process/(?P<pk>[0-9]+)/$', payment_api.as_view(), name="newplan_process"),
    url(r'^projectName/dvd_addon_pay/(?P<planid>[0-9]+)/(?P<cartid>[0-9]+)/(?P<dvd_quantity>[0-9]+)/(?P<amount>[0-9]+)/$', dvd_addon_pay.as_view(), name="dvd_addon_pay"),
    url(r'^projectName/invoice_history/(?P<pk>[0-9]+)/$', invoice_history.as_view(), name="invoice_history"),
    url(r'^projectName/newplan_payment/(?P<pk>[0-9]+)/(?P<pk1>[0-9]+)/$',newplan_payment, name='res'),
    url(r'^projectName/newplandvd_payment/(?P<pk>[0-9]+)/(?P<pk1>[0-9]+)/$',newplandvd_payment, name='newplandvd_payment'),
    url(r'^projectName/export_invoice/(?P<pk>[0-9]+)/$',export_invoice.as_view(), name='export_invoice'),
    url(r'^projectName/exportaddondvd_invoice/(?P<pk>[0-9]+)/$',exportaddondvd_invoice.as_view(), name='exportaddondvd_invoice'),
    url(r'^projectName/exportaddon_invoice/(?P<pk>[0-9]+)/$',exportaddon_invoice.as_view(), name='exportaddon_invoice'),
    # (?# url(r'^projectName/invoice_historyaddon/(?P<pk>[0-9]+)/$',invoice_historyaddon.as_view(), name='invoice_historyaddon'),)





]
