# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 05:28
from __future__ import unicode_literals

import data_documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataroom', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
            ],
        ),
        migrations.CreateModel(
            name='DataroomFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.FileField(blank=True, default='', null=True, upload_to=data_documents.models.store_dataroom_files)),
                ('index', models.IntegerField(default=0)),
                ('is_file_index', models.IntegerField(default=0)),
                ('parent_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_root_folder', models.BooleanField(default=False)),
                ('is_folder', models.BooleanField(default=False)),
                ('is_infected', models.BooleanField(default=False)),
                ('file_content_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_size', models.FloatField(blank=True, null=True)),
                ('pages', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('dataroom_folder_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('selected', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by_date', models.DateTimeField(auto_now_add=True)),
                ('is_view', models.BooleanField(default=False)),
                ('is_print', models.BooleanField(default=False)),
                ('is_download', models.BooleanField(default=False)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('conversion_path', models.FileField(blank=True, default='', null=True, upload_to=data_documents.models.store_dataroom_files)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_user', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_folder', to='data_documents.DataroomFolder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_folder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataroomViewerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=1000)),
                ('page_number', models.IntegerField()),
                ('expiring_url', models.CharField(blank=True, max_length=1000)),
                ('expiring_thumbnail_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FolderDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='file download', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='file print', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='file view', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndexDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_user', to='dataroom.Dataroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManageDataroomCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_details', to='data_documents.Categories')),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
