# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-01 11:20
from __future__ import unicode_literals

import data_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomfolder',
            name='conversion_path',
            field=models.FileField(blank=True, default='', null=True, upload_to=data_documents.models.store_dataroom_files),
        ),
        migrations.AlterField(
            model_name='dataroomfolder',
            name='path',
            field=models.FileField(blank=True, default='', null=True, upload_to=data_documents.models.store_dataroom_files),
        ),
    ]
