# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-20 12:45
from __future__ import unicode_literals

import data_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0003_auto_20200120_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomfolder',
            name='conversion_path',
            field=models.FileField(blank=True, default='', max_length='500', null=True, upload_to=data_documents.models.store_dataroom_files),
        ),
        migrations.AlterField(
            model_name='dataroomfolder',
            name='path',
            field=models.FileField(blank=True, default='', max_length='500', null=True, upload_to=data_documents.models.store_dataroom_files),
        ),
    ]
