# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0005_auto_20200720_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='access_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
