# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-08 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0015_dataroom_dataroom_namefront'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0006_dataroomfolder_access_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderDrmDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='drm download', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_drm', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_drm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
