# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0008_folderdeletedownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderdeletedownload',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
