# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0015_dataroom_dataroom_namefront'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0009_folderdeletedownload_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderOrFileCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('event', models.CharField(choices=[('1', 'Copy Folder'), ('2', 'Copy File'), ('3', 'None')], default='3', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_file_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderOrFileMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('event', models.CharField(choices=[('1', 'Move Folder'), ('2', 'Move File'), ('3', 'None')], default='3', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_file_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
