# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0016_auto_20200909_1247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0010_folderorfilecopy_folderorfilemove'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownloadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('event', models.CharField(default='bulk_download', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_file_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
