# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0011_bulkdownloadfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdownloadfiles',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
