# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0012_auto_20200909_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderorfilemove',
            name='event',
            field=models.CharField(choices=[('1', 'Moved Folder'), ('2', 'Move File'), ('3', 'None')], default='3', max_length=50),
        ),
    ]
