# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0013_auto_20200909_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdownloadfiles',
            name='created_date',
        ),
    ]
