# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0015_bulkdownloadfiles_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdownloadfiles',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
