# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0017_auto_20200921_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderorfilecopy',
            name='event',
            field=models.CharField(default='copy', max_length=50),
        ),
        migrations.AlterField(
            model_name='folderorfilemove',
            name='event',
            field=models.CharField(default='move', max_length=50),
        ),
    ]
