# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0018_auto_20200921_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderorfilecopy',
            name='event',
            field=models.CharField(choices=[('Copy Folder', 'Copy Folder'), ('Copy File', 'Copy File'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='folderorfilemove',
            name='event',
            field=models.CharField(choices=[('Moved Folder', 'Moved Folder'), ('Move File', 'Move File'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
