# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-22 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0022_auto_20200918_1948'),
        ('data_documents', '0019_auto_20200921_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folderupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('event', models.CharField(default='uploaded', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folderupload_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folderupload_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='folderorfilemove',
            name='event',
            field=models.CharField(choices=[('Move Folder', 'Move Folder'), ('Move File', 'Move File'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
