# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-23 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0022_auto_20200918_1948'),
        ('data_documents', '0020_auto_20200922_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulkuploadstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isuploadfail', models.BooleanField(default=False)),
                ('totalnumberoffiles', models.IntegerField(default=0)),
                ('totaluploadedfiles', models.IntegerField(default=0)),
                ('totalfailedfiles', models.IntegerField(default=0)),
                ('is_root_folder', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='batch upload', max_length=50)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('parentfolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
