# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0022_auto_20200918_1948'),
        ('data_documents', '0021_bulkuploadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folderuploadinbulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('event', models.CharField(default='file in batch upload', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bulkuploadstatus',
            name='isuploadfail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='folderuploadinbulk',
            name='bulkupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.Bulkuploadstatus'),
        ),
        migrations.AddField(
            model_name='folderuploadinbulk',
            name='dataroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
        migrations.AddField(
            model_name='folderuploadinbulk',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder'),
        ),
        migrations.AddField(
            model_name='folderuploadinbulk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
