# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0022_auto_20200924_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderdeletedownload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='folderorfilecopy',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='folderorfilemove',
            name='file_name',
        ),
    ]
