# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0022_auto_20200918_1948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0023_auto_20200924_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folderfailinbulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('is_folder', models.BooleanField(default=False)),
                ('event', models.CharField(default='file/folder fail in batch upload', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='totalfailedfolders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='totalnumberoffolders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='totaluploadedfolders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderuploadinbulk',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folderuploadinbulk',
            name='event',
            field=models.CharField(default='file/folder in batch upload', max_length=50),
        ),
        migrations.AddField(
            model_name='folderfailinbulk',
            name='bulkupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.Bulkuploadstatus'),
        ),
        migrations.AddField(
            model_name='folderfailinbulk',
            name='dataroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
        migrations.AddField(
            model_name='folderfailinbulk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
