# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0024_auto_20200924_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkActivityTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderOrFileMove')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_activity_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
