# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0025_bulkactivitytracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkactivitytracker',
            name='bulk_event',
        ),
        migrations.AddField(
            model_name='folderorfilemove',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
