# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0026_auto_20200924_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderorfilemove',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_event', to='data_documents.BulkActivityTracker'),
        ),
    ]
