# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0027_auto_20200924_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkactivitytracker',
            name='event',
            field=models.CharField(default='bulk_event_move', max_length=50),
        ),
        migrations.AddField(
            model_name='bulkactivitytracker',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkactivitytracker',
            name='total_files',
            field=models.IntegerField(default=0),
        ),
    ]
