# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0029_bulkactivitytracker_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderdeletedownload',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
        migrations.AddField(
            model_name='folderdownload',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
        migrations.AddField(
            model_name='folderdrmdownload',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
        migrations.AddField(
            model_name='folderorfilecopy',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
        migrations.AddField(
            model_name='folderprint',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
        migrations.AlterField(
            model_name='folderorfilemove',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
    ]
