# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0030_auto_20200925_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadfiles',
            name='bulk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker'),
        ),
    ]
