# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0031_bulkdownloadfiles_bulk_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdownloadfiles',
            name='file_name',
        ),
    ]
