# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0022_auto_20200918_1948'),
        ('data_documents', '0032_remove_bulkdownloadfiles_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkactivitytracker',
            name='is_calculated',
        ),
        migrations.RemoveField(
            model_name='bulkactivitytracker',
            name='total_files',
        ),
        migrations.AddField(
            model_name='bulkactivitytracker',
            name='check_dataroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_dataroom', to='dataroom.Dataroom'),
        ),
        migrations.AlterField(
            model_name='bulkactivitytracker',
            name='event',
            field=models.CharField(default='bulk_event_tracker', max_length=50),
        ),
    ]
