# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-25 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0033_auto_20200925_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkactivitytracker',
            name='check_dataroom',
        ),
    ]
