# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0034_remove_bulkactivitytracker_check_dataroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='uploadedin_batch',
            field=models.BooleanField(default=False),
        ),
    ]
