# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-29 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0035_dataroomfolder_uploadedin_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='is_deleted_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomfolder',
            name='permanent_deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
