# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0022_auto_20200918_1948'),
        ('data_documents', '0036_auto_20200929_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkactivitytracker',
            name='dataroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_dataroom', to='dataroom.Dataroom'),
        ),
    ]
