# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-07 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0022_auto_20200918_1948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0037_bulkactivitytracker_dataroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('Restore Folder', 'Restore Folder'), ('Restore File', 'Restore File'), ('None', 'None')], default='None', max_length=50)),
                ('bulk_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker')),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restore_file_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restore_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
