# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0039_bulkuploadstatus_notifymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='notifymember',
            field=models.BooleanField(default=False),
        ),
    ]
