# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0040_dataroomfolder_notifymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='deleteatdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
