# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-16 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0041_dataroomfolder_deleteatdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataroomfolder',
            name='deleteatdatetime',
        ),
    ]
