# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-11-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0042_remove_dataroomfolder_deleteatdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderfailinbulk',
            name='file_pathh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
