# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0043_folderfailinbulk_file_pathh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='processcomplete',
            field=models.BooleanField(default=False),
        ),
    ]
