# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-03-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0044_bulkuploadstatus_processcomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentpagecount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_count', models.CharField(max_length=50)),
                ('pages_count', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
            ],
        ),
    ]
