# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-09-25 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0028_auto_20210617_1523'),
        ('data_documents', '0045_documentpagecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownloadstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filecount', models.IntegerField(default=0)),
                ('successfilescount', models.IntegerField(default=0)),
                ('failfilecount', models.IntegerField(default=0)),
                ('downloaded', models.BooleanField(default=False)),
                ('readytodownload', models.BooleanField(default=False)),
                ('filename', models.CharField(blank=True, max_length=500, null=True)),
                ('downloadedcount', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
