# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-09-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0046_bulkdownloadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadfiles',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkDownloadstatus'),
        ),
    ]
