# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-09-29 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0028_auto_20210617_1523'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0047_bulkdownloadfiles_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownloadfailFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='bulk_download_fail', max_length=50)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkDownloadstatus')),
                ('bulk_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker')),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_filefail_dataroom', to='dataroom.Dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_failfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
