# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-05-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0048_bulkdownloadfailfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_index_report',
            field=models.BooleanField(default=False),
        ),
    ]
