# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-07-13 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0031_dataroom_eighty_percent_mail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_documents', '0049_bulkdownloadstatus_is_index_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataroomactivitymerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataroomMembersid', models.CharField(blank=True, max_length=500, null=True)),
                ('Voteactivityid', models.CharField(blank=True, max_length=500, null=True)),
                ('Updateactivityid', models.CharField(blank=True, max_length=500, null=True)),
                ('qnaactivityid', models.CharField(blank=True, max_length=500, null=True)),
                ('groupactivityid', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('BulkActivityTracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkActivityTracker')),
                ('BulkDownloadstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.BulkDownloadstatus')),
                ('Bulkuploadstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.Bulkuploadstatus')),
                ('DataroomView', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.DataroomView')),
                ('FolderDeleteDownload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderDeleteDownload')),
                ('FolderDownload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderDownload')),
                ('FolderDrmDownload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderDrmDownload')),
                ('FolderOrFileCopy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderOrFileCopy')),
                ('FolderOrFileMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderOrFileMove')),
                ('FolderPrint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderPrint')),
                ('FolderView', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.FolderView')),
                ('Folderupload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.Folderupload')),
                ('RestoreFiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.RestoreFiles')),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
