# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-11-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0050_dataroomactivitymerge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomfolder',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
