# Generated by Django 3.2.16 on 2023-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0051_auto_20221121_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_overview_report',
            field=models.BooleanField(default=False),
        ),
    ]
