# Generated by Django 3.2.16 on 2023-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0052_bulkdownloadstatus_is_overview_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_activity_by_date_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_activity_by_files_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_download_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_q_and_a_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_user_and_grp_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_user_and_status_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_voting_report',
            field=models.BooleanField(default=False),
        ),
    ]
