# Generated by Django 3.2.16 on 2023-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0053_auto_20230208_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_index_report_2',
            field=models.BooleanField(default=False),
        ),
    ]
