# Generated by Django 3.2.16 on 2023-07-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0054_bulkdownloadstatus_is_index_report_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
