# Generated by Django 3.2.16 on 2023-09-28 16:36

import data_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0055_bulkuploadstatus_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomfolder',
            name='path',
            field=models.FileField(blank=True, default='', max_length=500, null=True, storage='AzureMediaStorage1', upload_to=data_documents.models.store_dataroom_files),
        ),
    ]
