# Generated by Django 3.2.16 on 2023-09-28 16:51

import data_documents.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0056_alter_dataroomfolder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomfolder',
            name='path',
            field=data_documents.models.FileField(blank=True, default='', max_length=500, null=True, upload_to=data_documents.models.store_dataroom_files),
        ),
    ]
