# Generated by Django 3.2.16 on 2024-06-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0035_otp_model'),
        ('data_documents', '0057_alter_dataroomfolder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redacted_Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('file', models.CharField(blank=True, max_length=100000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_version', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.FloatField(blank=True, null=True)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted_permanent', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.dataroom')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_redect', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_documents.dataroomfolder')),
                ('permanent_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_deleted_by_redect', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedactorVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='redacted', max_length=50)),
                ('event1', models.CharField(default='redact', max_length=50)),
                ('bulk_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.bulkactivitytracker')),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redacted_d', to='dataroom.dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.dataroomfolder')),
                ('redact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.redacted_pdf')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redacted_u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_single', models.BooleanField(blank=True, default=False, null=True)),
                ('is_folder', models.BooleanField(blank=True, default=False, null=True)),
                ('is_file', models.BooleanField(blank=True, default=False, null=True)),
                ('is_show', models.BooleanField(blank=True, default=False, null=True)),
                ('unique_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_restored', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deleted_permanent', models.BooleanField(blank=True, default=False, null=True)),
                ('dataroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.dataroom')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.dataroomfolder')),
                ('is_deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder_trash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_trash_parent', to='data_documents.foldertrash')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.dataroom')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_documents.dataroomfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
