# Generated by Django 3.2.25 on 2024-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0058_favourite_foldertrash_redacted_pdf_redactorversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='is_compatable',
            field=models.BooleanField(default=True),
        ),
    ]
