# Generated by Django 3.2.25 on 2025-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0059_dataroomfolder_is_compatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_single_file',
            field=models.BooleanField(default=False),
        ),
    ]
