# Generated by Django 3.2.25 on 2025-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0060_bulkdownloadstatus_is_single_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadstatus',
            name='is_file_irm',
            field=models.BooleanField(default=False),
        ),
    ]
