# Generated by Django 3.2.25 on 2026-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0061_bulkdownloadstatus_is_file_irm'),
    ]

    operations = [
        migrations.CreateModel(
            name='azure_token_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('access_token_date', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_date', models.DateTimeField(blank=True, null=True)),
                ('is_email', models.BooleanField(default=False)),
                ('is_drm', models.BooleanField(default=False)),
            ],
        ),
    ]
