# Generated by Django 3.2.25 on 2026-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0062_azure_token_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azure_token_model',
            name='access_token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='azure_token_model',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
