from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^projectName/get_end_user_groups/(?P<pk>[0-9]+)/$', GetEndUserGroup.as_view(), name="get_end_user_groups"),
    url(r'^projectName/check_admin/$', CheckAdmin.as_view(), name="check_admin"),
    url(r'^projectName/check_admin_user/$', CheckAdminUser.as_view(), name="check_admin_user"),    
    url(r'^projectName/check_la_user/$', CheckLaUser.as_view(), name="check_la_user"),    
    url(r'^projectName/create_dataroom_admin/(?P<pk>[0-9]+)/$', CreateDataroomAdmin.as_view(), name="create_dataroom_admin"),    
    url(r'^projectName/create_dataroom_la_group/(?P<pk>[0-9]+)/$', CreateDataroomLaGroup.as_view(), name='create_dataroom_la_group'),
    url(r'^projectName/add_dataroom_la_user_group/(?P<pk>[0-9]+)/$', AddDataroomLaUserGroup.as_view(), name='add_dataroom_la_user_group'),  
    url(r'^projectName/create_dataroom_enduser_group/(?P<pk>[0-9]+)/$', CreateDataroomEndUserGroup.as_view(), name='create_dataroom_end_user_group'),
    url(r'^projectName/delete_dataroom_admins/(?P<pk>[0-9]+)/$', DeleteDataroomAdmins.as_view(), name='delete_dataroom_admins'), 
    url(r'^projectName/delete_dataroom_admin_type/(?P<pk>[0-9]+)/$', DeleteTypeDataroomAdmins.as_view(), name='delete_dataroom_admin_type'),
    url(r'^projectName/user_and_perm_bulk_delete/(?P<pk>[0-9]+)/(?P<pk1>[0-9]+)/$', BulkDeleteTypeDataroomAdmins.as_view(), name='bulk_delete_dataroom_admin_type'),
    # url(r'^projectName/bulk_delete_dataroom_admin_type/(?P<pk>[0-9]+)/$', BulkDeleteTypeDataroomAdmins.as_view(), name='bulk_delete_dataroom_admin_type'),
    url(r'^projectName/delete_dataroom_all_admins/$', DeleteDataroomAllAdmins.as_view(), name='delete_dataroom_all_admins'),     
    url(r'^projectName/get_end_user_information/(?P<pk>[0-9]+)/$', GetEndUserGroupInformation.as_view(), name='get_end_user_information'), 
    url(r'^projectName/get_firstname_and_lastname_using_emailid/$', GetFirstNameAndLastNameUsingEmail.as_view(), name='get_firstname_and_lastname_using_emailid'),
    url(r'^projectName/get_users_and_permission_data/(?P<pk>[0-9]+)/$', GetUsersAndPermissionData.as_view(), name='get_users_and_permission_data'),
    url(r'^projectName/resend_invitation_link/$', ResendInvitationLink.as_view(), name='resend_invitation_link'),
    url(r'^projectName/all_end_users/(?P<pk>[0-9]+)/$', GetAllEndUsers.as_view(), name='all_end_users'),  
    url(r'^projectName/get_members_permission/(?P<pk>[0-9]+)/$', GetMembersPermission.as_view(), name='get_members_permission'),  
    url(r'^projectName/create_dataroom_folder_permission/(?P<pk>[0-9]+)/$', CreateDataroomGroupFolderPermissions.as_view(), name='create_dataroom_folder_permission'),
    url(r'^projectName/create_dataroom_folder_permission_for_time/(?P<pk>[0-9]+)/$', CreateDataroomGroupFolderPermissionsForTime.as_view(), name='create_dataroom_folder_permission'),
    url(r'^projectName/get_groups/(?P<pk>[0-9]+)/$', GetGroupReports.as_view(), name='get_groups'),
    url(r'^projectName/get_user_groups/(?P<pk>[0-9]+)/$', GetUsersGroupReports.as_view(), name='get_users_groups'),
    url(r'^projectName/get_user_dataroom_last_view/(?P<pk>[0-9]+)/(?P<user>[0-9]+)/$', GetLastDataroomView.as_view(), name='get_user_dataroom_last_view'),
    url(r'^projectName/export_users_groups/(?P<pk>[0-9]+)/$', ExportUsersGroups.as_view(), name='export_users_groups'),
    url(r'^projectName/get_users_status/(?P<pk>[0-9]+)/$', GetUsersStatus.as_view(), name='get_users_status'),
    url(r'^projectName/export_users_status/(?P<pk>[0-9]+)/$', ExportUsersStatus.as_view(), name='export_users_status'),
    url(r'^projectName/dataroom_group_list/(?P<pk>[0-9]+)/$', DataroomGroupList.as_view()), 
    url(r'^projectName/add_dataroom_primary_contact/(?P<pk>[0-9]+)/$', AddDataroomPrimaryContact.as_view()),
    url(r'^projectName/get_dataroon_contact/(?P<pk>[0-9]+)/$', GetDataroonContact.as_view()),
    url(r'^projectName/get_all_primary_users/(?P<pk>[0-9]+)/$', GetAllPrimaryUser.as_view()),
    url(r'^projectName/change_disclaimer_status/$', ChangeDisclaimerStatus.as_view()),
    url(r'^projectName/dataroom_enduser_submitter/$', DataroomEndUserSubmitter.as_view(), name='dataroom_enduser_submitter'),     
    url(r'^projectName/user_by_email/$', UserByEmail.as_view(), name='user_by_email'),  
    url(r'^projectName/all_groups/(?P<pk>[0-9]+)/$', AllGroups.as_view(), name='all_groups'),  
    url(r'^projectName/search_auto_complete_user/$', SearchAutoCompleteUser.as_view(), name='search_auto_complete_user'),  
    url(r'^projectName/GroupDeactivateactivate/(?P<pk>[0-9]+)/$', GroupDeactivateactivate.as_view(), name='GroupDeactivateactivate'),  
    url(r'^projectName/get_group_details/(?P<pk>[0-9]+)/$', Get_group_details.as_view(), name='get_group_details'),  
    url(r'^projectName/irm_group_protection/(?P<pk>[0-9]+)/$', Irm_group_protection.as_view(), name='Irm_group_protection'),  


]
