# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-13 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qna', '__first__'),
        ('data_documents', '0040_dataroomfolder_notifymember'),
        ('users_and_permission', '0007_dataroommembers_event_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0023_auto_20201008_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('dataroom_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_documents.DataroomFolder')),
                ('dataroom_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomGroups')),
                ('dataroom_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomMembers')),
                ('dataroom_updates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.RcentUpdate')),
                ('qna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.QuestionAnswer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_message', models.CharField(max_length=2000)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('main', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.Message')),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_rec', to=settings.AUTH_USER_MODEL)),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('send_notification_members', models.BooleanField(default=False)),
                ('use_file_workshop_home', models.BooleanField(default=False)),
                ('hide_file_index_admin', models.BooleanField(default=False)),
                ('workspace_name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('dataroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
