# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_documents', '0040_dataroomfolder_notifymember'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotifications',
            name='bulkuploadd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulkuploddataishere', to='data_documents.Bulkuploadstatus'),
        ),
    ]
