# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-30 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_allnotifications_bulkuploadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='latestsender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latestmessage_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
