# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-11-04 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_message_latestsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='latestmessage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
