# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-02-25 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_allnotifications_dataroom_member_invitation_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnotifications',
            name='dataroom_member_invitation_accept',
        ),
    ]
