# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-02-25 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0046_user_notify_recieved'),
        ('notifications', '0006_remove_allnotifications_dataroom_member_invitation_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotifications',
            name='dataroom_member_invitation_accept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.InviteUser'),
        ),
    ]
