# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-27 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userauth.managers
import userauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('avatar', models.ImageField(blank=True, default='default_images/user-icon.png', null=True, upload_to=userauth.models.user_directory_path_for_profile)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_subscriber', models.BooleanField(default=False)),
                ('is_end_user', models.BooleanField(default=False)),
                ('is_team', models.BooleanField(default=False)),
                ('is_team_member', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
                ('is_icon_downloaded', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('agree', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', userauth.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_ip', models.CharField(max_length=100)),
                ('logged_in_time', models.DateTimeField()),
                ('logged_out_time', models.DateTimeField()),
                ('is_logged_in', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndUserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user_types', models.CharField(blank=True, max_length=1000)),
                ('is_dataroom_admin', models.BooleanField(default=False)),
                ('is_dataroom_la_admin', models.BooleanField(default=False)),
                ('is_dataroom_enduser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InviteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitatation_sent_date', models.DateTimeField(auto_now_add=True)),
                ('invitatation_acceptance_date', models.DateTimeField(auto_now_add=True)),
                ('is_invitation_accepted', models.BooleanField(default=False)),
                ('is_invitation_expired', models.BooleanField(default=False)),
                ('invitation_link', models.CharField(blank=True, max_length=1000)),
                ('invitation_token', models.CharField(blank=True, max_length=1000)),
                ('dataroom_invitation', models.IntegerField(blank=True, null=True)),
                ('dataroom', models.IntegerField(blank=True, null=True)),
                ('invitation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.InvitationStatus')),
                ('invitiation_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitiation_receiver', to=settings.AUTH_USER_MODEL)),
                ('invitiation_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitiation_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=400)),
                ('is_activation_key_status', models.BooleanField(default=False)),
                ('is_reset_key_status', models.BooleanField(default=False)),
                ('reset_key', models.CharField(max_length=500)),
                ('key_expires', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'member'), (2, 'dataroom_admin'), (3, 'super_admin'), (4, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='userauth.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
