# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteuser',
            name='dataroom',
        ),
        migrations.AlterField(
            model_name='inviteuser',
            name='invitatation_acceptance_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
