# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200302_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteuser',
            name='dataroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
