# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-04 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_inviteuser_dataroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteuser',
            name='dataroom',
        ),
    ]
