# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_permission', '0006_remove_rcentupdate_text1'),
        ('userauth', '0004_remove_inviteuser_dataroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendinginvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_end_user', models.BooleanField(default=False)),
                ('emailsendflag', models.BooleanField(default=False)),
                ('dataroom_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataroomgroupPI', to='users_and_permission.DataroomGroups')),
            ],
        ),
    ]
