# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0016_auto_20200909_1247'),
        ('userauth', '0005_pendinginvitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginvitations',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
    ]
