# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_pendinginvitations_dataroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinginvitations',
            name='dataroom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_and_permission.DataroomGroups'),
        ),
    ]
