# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_auto_20200912_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/defaultprofilepic.png', null=True, upload_to=userauth.models.user_directory_path_for_profile),
        ),
    ]
