# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20200916_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteuser',
            name='is_shifted',
            field=models.BooleanField(default=False),
        ),
    ]
