# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_inviteuser_is_shifted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginvitations',
            name='usertype',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
