# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-06 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_pendinginvitations_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinginvitations',
            name='usertype',
        ),
        migrations.AddField(
            model_name='pendinginvitations',
            name='is_la_user',
            field=models.BooleanField(default=False),
        ),
    ]
