# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-20 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_auto_20201006_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginvitations',
            name='senderuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
