# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_pendinginvitations_senderuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginvitations',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
