# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-11-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_pendinginvitations_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
