# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_planinvoiceuserwise'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriptionplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('storage', models.CharField(blank=True, max_length=1000, null=True)),
                ('users', models.CharField(blank=True, max_length=1000, null=True)),
                ('term', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planinvoiceuserwise',
            name='selected_plan',
        ),
    ]
