# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0018_auto_20201208_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.subscriptionplan'),
        ),
    ]
