# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0019_planinvoiceuserwise_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='selected_plan',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
