# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-10 22:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0020_planinvoiceuserwise_selected_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='plansfeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('desciption', ckeditor.fields.RichTextField(blank=True, help_text='Please fill this field', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='datarooms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='planstatus',
            field=models.BooleanField(default=False),
        ),
    ]
