# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0022_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
