# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0023_user_paid_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='datarooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
