# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0024_auto_20201211_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
