# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-23 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0025_user_start_email_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='addon_plan_invoiceuserwise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_plan', models.CharField(blank=True, max_length=1000, null=True)),
                ('edition', models.CharField(blank=True, max_length=1000, null=True)),
                ('select_billing_term', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=1000, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=1000, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=1000, null=True)),
                ('po_box', models.CharField(blank=True, max_length=1000, null=True)),
                ('effective_price', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_fee', models.CharField(blank=True, max_length=1000, null=True)),
                ('vat', models.CharField(blank=True, max_length=1000, null=True)),
                ('grand_total', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_option', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='addon_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('datarooms', models.IntegerField(blank=True, null=True)),
                ('users', models.CharField(blank=True, max_length=1000, null=True)),
                ('term', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('planstatus', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansfeature',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
