# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0027_addon_plan_invoiceuserwise_addon_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='is_plan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='is_plan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
