# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0028_auto_20201228_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon_plan_invoiceuserwise',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon_plan_invoiceuserwise',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planinvoiceuserwise',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planinvoiceuserwise',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
