# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0029_auto_20201228_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
