# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0023_auto_20201008_1514'),
        ('userauth', '0030_user_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom'),
        ),
    ]
