# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0031_auto_20210105_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='addon_plans',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='effective_price',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='payment_complete',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='po_box',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='select_billing_term',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='selected_plan',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='addon_plan_invoiceuserwise',
            name='vat',
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='addon_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.addon_plans'),
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='addon_plans',
            field=models.ManyToManyField(blank=True, null=True, to='userauth.addon_plan_invoiceuserwise'),
        ),
    ]
