# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-06 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0023_auto_20201008_1514'),
        ('userauth', '0032_auto_20210105_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='dvd_addon_invoiceuserwise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_calceled', models.BooleanField(default=False)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dvd_addon_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('hardware_medium', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('planstatus', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
