# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0033_dvd_addon_invoiceuserwise_dvd_addon_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd_addon_invoiceuserwise',
            name='dvd_addon_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.dvd_addon_plans'),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='dvd_addon_plans',
            field=models.ManyToManyField(blank=True, null=True, to='userauth.dvd_addon_invoiceuserwise'),
        ),
    ]
