# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-11 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0023_auto_20201008_1514'),
        ('userauth', '0034_auto_20210106_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='addon_plan_tempforsameday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_plan_active', models.BooleanField(default=False)),
                ('user_undo_upload', models.BooleanField(default=False)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('addon_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.addon_plans')),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Dataroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
