# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0035_addon_plan_tempforsameday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planinvoiceuserwise',
            name='addon_plans',
            field=models.ManyToManyField(blank=True, to='userauth.addon_plan_invoiceuserwise'),
        ),
        migrations.AlterField(
            model_name='planinvoiceuserwise',
            name='dvd_addon_plans',
            field=models.ManyToManyField(blank=True, to='userauth.dvd_addon_invoiceuserwise'),
        ),
    ]
