# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0036_auto_20210111_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
