# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0037_planinvoiceuserwise_auto_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='cancel_at_monthend',
            field=models.BooleanField(default=False),
        ),
    ]
