# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0038_planinvoiceuserwise_cancel_at_monthend'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='is_plan_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
