# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0039_planinvoiceuserwise_is_plan_upgraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='is_latest_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
