# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-21 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0040_planinvoiceuserwise_is_latest_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd_addon_invoiceuserwise',
            name='is_delivered',
        ),
    ]
