# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0041_remove_dvd_addon_invoiceuserwise_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd_addon_invoiceuserwise',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=50),
        ),
    ]
