# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-27 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0042_dvd_addon_invoiceuserwise_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='telr_payment_cartids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_plan', models.BooleanField(default=False)),
                ('is_DVD_addon', models.BooleanField(default=False)),
                ('is_storage_addon', models.BooleanField(default=False)),
                ('telr_ref_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dvd_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.dvd_addon_invoiceuserwise')),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.planinvoiceuserwise')),
                ('storage_addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.addon_plan_invoiceuserwise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
