# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0043_telr_payment_cartids'),
    ]

    operations = [
        migrations.AddField(
            model_name='telr_payment_cartids',
            name='is_payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
