# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0044_telr_payment_cartids_is_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='project_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
