# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-02-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0045_planinvoiceuserwise_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_recieved',
            field=models.BooleanField(default=True),
        ),
    ]
