# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-22 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0046_user_notify_recieved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='telr_payment_cartids',
            new_name='ccavenue_payment_cartids',
        ),
    ]
