# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-22 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0047_auto_20210422_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccavenue_payment_cartids',
            old_name='telr_ref_id',
            new_name='ref_id',
        ),
    ]
