# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0048_auto_20210422_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccavenue_payment_cartids',
            name='bank_ref_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
