# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0049_ccavenue_payment_cartids_bank_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccavenue_payment_cartids',
            name='si_ref_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
