# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0050_ccavenue_payment_cartids_si_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='ccavenue_cartid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='planid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccavenue_payment_cartids',
            name='bank_mid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ccavenue_payment_cartids',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ccavenue_payment_cartids',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dvd_addon_invoiceuserwise',
            name='ccavenue_cartid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dvd_addon_invoiceuserwise',
            name='planid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='ccavenue_cartid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
