# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0051_auto_20210428_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
