# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0052_addon_plan_invoiceuserwise_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='new_invoiceid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='plan_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
