# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0053_auto_20210428_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
