# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0054_planinvoiceuserwise_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='is_payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addon_plan_tempforsameday',
            name='entry_used',
            field=models.BooleanField(default=False),
        ),
    ]
