# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0055_auto_20210505_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
