# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0056_auto_20210506_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_plan_invoiceuserwise',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planinvoiceuserwise',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
