# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0057_auto_20210514_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='userauth.Role'),
        ),
    ]
