# Generated by Django 3.2.16 on 2023-05-17 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0031_dataroom_eighty_percent_mail'),
        ('userauth', '0058_auto_20210521_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='otp_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_verifed', models.BooleanField(default=False)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.dataroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
