# Generated by Django 3.2.16 on 2024-01-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0059_auto_20230517_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesshistory',
            name='logged_out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='otp_model',
        ),
    ]
