# Generated by Django 3.2.16 on 2024-01-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0060_auto_20240117_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_password_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
