# Generated by Django 3.2.16 on 2024-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0061_user_password_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=400)),
            ],
        ),
    ]
