# Generated by Django 3.2.16 on 2024-02-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0062_captcha_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha_model',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
