# Generated by Django 3.2.16 on 2024-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0063_captcha_model_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='salt_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_code', models.CharField(max_length=400)),
            ],
        ),
    ]
