# Generated by Django 3.2.16 on 2024-02-23 14:09

from django.db import migrations, models
import dms.custom_azure
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0064_salt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/defaultprofilepic.png', null=True, storage=dms.custom_azure.AzureMediaStorage, upload_to=userauth.models.user_directory_path_for_profile),
        ),
    ]
