# Generated by Django 3.2.16 on 2024-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0065_auto_20240223_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_trails',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
