# Generated by Django 3.2.16 on 2024-02-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0066_user_login_trails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_trails',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='forget_trails_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
