# Generated by Django 3.2.25 on 2024-11-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0069_timezoneslist_user_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezoneslist',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
