# Generated by Django 3.2.25 on 2025-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0070_timezoneslist_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
